runtime: nodejs18

service: syosetu2epub-api

env_variables:
  NODE_ENV: production
  PORT: 8080

automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

handlers:
  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301

# 確保包含必要的靜態檔案
skip_files:
  - ^(.*/)?#.*#$
  - ^(.*/)?.*~$
  - ^(.*/)?.*\.py[co]$
  - ^(.*/)?.*/RCS/.*$
  - ^(.*/)?\..*$
  - ^(.*/)?tests?/.*$
  - ^(.*/)?test/.*$
  - ^(.*/)?node_modules/.*$
  - ^(.*/)?src/.*$
  - ^(.*/)?.*\.ts$
  - ^(.*/)?.*\.md$
